apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-sp-paragrafikode
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  protected: true
  accessPolicy:
    outbound:
      external:
        - host: api-gw.oera.no
        - host: login.microsoftonline.com
  env:
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw.oera.no/security-token-service
    - name: MEDLEMSKAPVURDERT_ENABLED
      value: Nei
